### ISSUE TITLE
Model changes

### ISSUE THREAD

**Issue by Nosk14** [petconnection/backend#16]
BaseClass needs to be removed from the models because a table is created in the database just for a name field.

In addition, we should add a field in Animal to store its birthdate.

**Comment by pablo-grande** [comment]
Remember to add the `name` in those child, and soon to be orphaned, tables :wink:

**Comment by pablo-grande** [comment]
There is no way of editing a species field with our auto generated Django backend:
![missing](https://user-images.githubusercontent.com/5110926/38321355-b2c0cae0-3837-11e8-8258-f8b03cec1882.png)

A possible solution would be to create a field (not a property) in the animal model, keep that in mind for the next model migration.
