### ISSUE TITLE
Medical record filters if it is null

### ISSUE THREAD

**Issue by Nosk14** [petconnection/backend#20]
Now we have the filters is_castrated and has_chip that filter animals depending on the values stored in the its medical record. But there is a problem with this: If the animal does not have a medical record, if you one of those filters, this animal will never appear in the result regardless of the value you are using to filter.

So, what is the expected behavior in this case? Leave it like this or treat this "unknown state" with some default values (like assume the animal has no chip)?

**Comment by pablo-grande** [comment]
In #18 the creation of an animal implies the creation of a medical record associated to the animal, even if it empty. So this won't be a problem for user created animals.
