### ISSUE TITLE
Unknown breed

### ISSUE THREAD

**Issue by pablo-grande** [petconnection/backend#6]
Solving issue #5 I realized the `breed_field` is mandatory, but sometimes it is hard to determine the breed of a dog. Should we keep it like this? or should we put in the DB an 'unknown' breed?

**Comment by Nosk14** [comment]
I think you should try to set the breed that most resembles to the animal, but I know it is sometimes hard to do. So, creating an unknown breed could be a fine solution.

**Comment by marc-ferrer** [comment]
The breed of an animal is not always clear, some of them don't even fall into the definition of breed, it could also be a mix of 2 or more. `unknown` seems alright and I would not add any kind strict validation to that field either.
