### ISSUE TITLE
Response Json format

### ISSUE THREAD

**Issue by Nosk14** [petconnection/backend#9]
Now, the API returns a list of animals like this:
```json
[
    {
        "name" : "Popeye",
        "entity" : 0
    },
    {
        "name" : "Olivia",
        "entity" : 2
    }
]
```
This is god for representing the list of animals, but I think in the future we will need to return some metainfo like total number of animals, pagination info, and something like that. Or maybe just an error field. For these reasons, I prupose to encapsulate the list into an other field to have a top level space to add more fields:

```json
{
    "some_other_fields" : "value",
     "animals": [
                    {
                        "name" : "Popeye",
                        "entity" : 0
                    },
                    {
                        "name" : "Olivia",
                        "entity" : 2
                    }
                ]
}
```

The same can be applied to entities.
What do you think about it?

**Comment by pablo-grande** [comment]
![](https://media.giphy.com/media/j2PS9MGm85WkE/giphy.gif)
